<?php
$labels = array();
$labels['changesound'] = 'إشعار البريد الإلكتروني المخصص';
$labels['uploadsound'] = 'تحميل ملف صوتي';
$labels['currentsound'] = 'إشعار البريد الإلكتروني الحالي';
$labels['remove'] = 'إزالة';
$labels['save'] = 'الحفظ';
$labels['invalidtype'] = 'نوع الملف غير صالح. مسموح به: mp3، ogg، flac، wav، m4a';
$labels['toosmall'] = 'تحميل فارغ أو ملف صغير جداً.';
$labels['toolarge'] = 'الملف كبير جداً';
$labels['savesuccess'] = 'تم تحديث إشعار البريد الإلكتروني المخصص.';
$labels['removesuccess'] = 'تمت إزالة إشعار البريد الإلكتروني المخصص.';
$labels['playtest'] = 'إشعار التشغيل';
$labels['hint'] = 'يؤدي هذا إلى تجاوز صوت الرسالة الجديدة الافتراضي عند تمكين "تشغيل الصوت على الرسالة الجديدة".';
?>
