<?php
// Català (Espanya)

$labels = [
  'changesound'   => 'Notificació de correu electrònic personalitzada',
  'uploadsound'   => 'Puja un fitxer d’àudio',
  'currentsound'  => 'Notificació de correu electrònic actual',
  'remove'        => 'Elimina',
  'save'          => 'Desa',
  'invalidtype'   => 'Tipus de fitxer no vàlid. Formats permesos: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'La càrrega està buida o el fitxer és massa petit.',
  'toolarge'      => 'El fitxer és massa gran.',
  'savesuccess'   => 'La notificació de correu electrònic personalitzada s’ha actualitzat.',
  'removesuccess' => 'La notificació de correu electrònic personalitzada s’ha eliminat.',
  'playtest'      => 'Reprodueix notificació',
  'hint'          => 'Això substitueix el so per defecte dels missatges nous quan l’opció «Reproduir so en rebre un missatge nou» està activada.',
];
