<?php
// Čeština (Česká republika)

$labels = array();
$labels['changesound']   = 'Vlastní e-mailové upozornění';
$labels['uploadsound']   = 'Nahrát zvukový soubor';
$labels['currentsound']  = 'Aktuální e-mailové upozornění';
$labels['remove']        = 'Odstranit';
$labels['save']          = 'Uložit';
$labels['invalidtype']   = 'Nesprávný typ souboru. Povolené: mp3, ogg, flac, wav, m4a';
$labels['toosmall']      = 'Prázdné nahrávání nebo soubor je příliš malý.';
$labels['toolarge']      = 'Soubor je příliš velký.';
$labels['savesuccess']   = 'Vlastní e-mailové upozornění bylo aktualizováno.';
$labels['removesuccess'] = 'Vlastní e-mailové upozornění bylo odstraněno.';
$labels['playtest']      = 'Přehrát upozornění';
$labels['hint']          = 'Tímto se přepíše výchozí zvuk pro nové zprávy, když je povolena možnost „Přehrát zvuk při nové zprávě“.';
?>
