<?php
// Cymraeg (Y Deyrnas Unedig)

$labels = [
  'changesound'   => 'Hysbysiad e-bost personol',
  'uploadsound'   => 'Uwchlwytho ffeil sain',
  'currentsound'  => 'Hysbysiad e-bost cyfredol',
  'remove'        => 'Dileu',
  'save'          => 'Cadw',
  'invalidtype'   => 'Math ffeil annilys. Caniataol: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Uwchlwythiad gwag neu ffeil rhy fach.',
  'toolarge'      => 'Mae’r ffeil yn rhy fawr.',
  'savesuccess'   => 'Diweddarwyd yr hysbysiad e-bost personol.',
  'removesuccess' => 'Tynnwyd yr hysbysiad e-bost personol.',
  'playtest'      => 'Chwarae hysbysiad',
  'hint'          => 'Mae hyn yn disodli’r sain rhagosodedig ar gyfer neges newydd pan fo’r opsiwn “Chwarae sain pan ddaw neges newydd” wedi’i alluogi.',
];
