<?php
// Dansk (Danmark)

$labels = array();
$labels['changesound']   = 'Brugerdefineret e-mail-underretning';
$labels['uploadsound']   = 'Upload lydfil';
$labels['currentsound']  = 'Aktuel e-mail-underretning';
$labels['remove']        = 'Fjern';
$labels['save']          = 'Gem';
$labels['invalidtype']   = 'Ugyldig filtype. Tilladt: mp3, ogg, flac, wav, m4a';
$labels['toosmall']      = 'Tom upload eller filen er for lille.';
$labels['toolarge']      = 'Filen er for stor.';
$labels['savesuccess']   = 'Brugerdefineret e-mail-underretning er blevet opdateret.';
$labels['removesuccess'] = 'Brugerdefineret e-mail-underretning er blevet fjernet.';
$labels['playtest']      = 'Afspil meddelelse';
$labels['hint']          = 'Dette tilsidesætter standardlyden for nye beskeder, når "Afspil lyd ved ny besked" er aktiveret.';
?>
