<?php
$labels = array();
$labels['changesound']   = 'Notificación de correo personalizada';
$labels['uploadsound']   = 'Cargar archivo de audio';
$labels['currentsound']  = 'Notificación de correo actual';
$labels['remove']        = 'Eliminar';
$labels['save']          = 'Guardar';
$labels['invalidtype']   = 'Tipo de archivo no válido. Permitidos: mp3, ogg, flac, wav, m4a';
$labels['toosmall']      = 'Archivo vacío o demasiado pequeño.';
$labels['toolarge']      = 'El archivo es demasiado grande.';
$labels['savesuccess']   = 'La notificación de correo personalizada se actualizó.';
$labels['removesuccess'] = 'La notificación de correo personalizada se eliminó.';
$labels['playtest']      = 'Reproducir notificación';
$labels['hint']          = 'Esto reemplaza el sonido predeterminado de nuevo mensaje cuando está habilitada la opción «Reproducir sonido en nuevo mensaje».';
?>
