<?php
// Eesti (Eesti)

$labels = array();
$labels['changesound']   = 'Kohandatud e-posti teavitus';
$labels['uploadsound']   = 'Laadi üles helifail';
$labels['currentsound']  = 'Praegune e-posti teavitus';
$labels['remove']        = 'Eemalda';
$labels['save']          = 'Salvesta';
$labels['invalidtype']   = 'Sobimatu failitüüp. Lubatud: mp3, ogg, flac, wav, m4a';
$labels['toosmall']      = 'Tühi üleslaadimine või fail on liiga väike.';
$labels['toolarge']      = 'Fail on liiga suur.';
$labels['savesuccess']   = 'Kohandatud e-posti teavitus on uuendatud.';
$labels['removesuccess'] = 'Kohandatud e-posti teavitus on eemaldatud.';
$labels['playtest']      = 'Esita teavitus';
$labels['hint']          = 'See asendab uue sõnumi vaikimisi heli, kui suvand „Esita heli uue sõnumi korral” on lubatud.';
?>
