<?php
// Français (Canada)

$labels = [
  'changesound'   => 'Notification courriel personnalisée',
  'uploadsound'   => 'Téléverser un fichier audio',
  'currentsound'  => 'Notification courriel actuelle',
  'remove'        => 'Supprimer',
  'save'          => 'Enregistrer',
  'invalidtype'   => 'Type de fichier non valide. Autorisés : mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Téléversement vide ou fichier trop petit.',
  'toolarge'      => 'Fichier trop gros.',
  'savesuccess'   => 'Notification courriel personnalisée mise à jour.',
  'removesuccess' => 'Notification courriel personnalisée supprimée.',
  'playtest'      => 'Lire la notification',
  'hint'          => 'Ceci remplace le son par défaut du nouveau message lorsque « Lire le son à la réception d’un nouveau message » est activé.',
];
