<?php
// Français (Luxembourg)

$labels = [
  'changesound'   => 'Notification e-mail personnalisée',
  'uploadsound'   => 'Importer un fichier audio',
  'currentsound'  => 'Notification e-mail actuelle',
  'remove'        => 'Supprimer',
  'save'          => 'Enregistrer',
  'invalidtype'   => 'Type de fichier non valide. Autorisés : mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Importation vide ou fichier trop petit.',
  'toolarge'      => 'Fichier trop grand.',
  'savesuccess'   => 'La notification e-mail personnalisée a été mise à jour.',
  'removesuccess' => 'La notification e-mail personnalisée a été supprimée.',
  'playtest'      => 'Lire la notification',
  'hint'          => 'Ceci remplace le son par défaut d’un nouveau message lorsque l’option « Lire le son à la réception d’un nouveau message » est activée.',
];
