<?php
// Hrvatski (Hrvatska)

$labels = [
  'changesound'   => 'Prilagođena obavijest e-pošte',
  'uploadsound'   => 'Učitaj audio datoteku',
  'currentsound'  => 'Trenutna obavijest e-pošte',
  'remove'        => 'Ukloni',
  'save'          => 'Spremi',
  'invalidtype'   => 'Nevažeća vrsta datoteke. Dozvoljeni formati: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Prazna datoteka ili datoteka je premala.',
  'toolarge'      => 'Datoteka je prevelika.',
  'savesuccess'   => 'Prilagođena obavijest e-pošte je uspješno ažurirana.',
  'removesuccess' => 'Prilagođena obavijest e-pošte je uspješno uklonjena.',
  'playtest'      => 'Reproduciraj obavijest',
  'hint'          => 'Ova opcija zamjenjuje zadani zvuk nove poruke kada je uključeno „Reproduciraj zvuk za novu poruku“.',
];
