<?php
// Magyar (Magyarország)

$labels = [
  'changesound'   => 'Személyre szabott e-mail értesítés',
  'uploadsound'   => 'Hangfájl feltöltése',
  'currentsound'  => 'Aktuális e-mail értesítés',
  'remove'        => 'Eltávolítás',
  'save'          => 'Mentés',
  'invalidtype'   => 'Érvénytelen fájltípus. Engedélyezett formátumok: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Üres feltöltés vagy túl kicsi fájl.',
  'toolarge'      => 'A fájl túl nagy.',
  'savesuccess'   => 'A személyre szabott e-mail értesítés sikeresen frissítve.',
  'removesuccess' => 'A személyre szabott e-mail értesítés sikeresen eltávolítva.',
  'playtest'      => 'Értesítés lejátszása',
  'hint'          => 'Ez felülírja az alapértelmezett új üzenet hangját, ha az „Új üzenetnél hang lejátszása” engedélyezve van.',
];
