<?php
// Bahasa Indonesia (Indonesia)

$labels = [
  'changesound'   => 'Notifikasi email kustom',
  'uploadsound'   => 'Unggah file audio',
  'currentsound'  => 'Notifikasi email saat ini',
  'remove'        => 'Hapus',
  'save'          => 'Simpan',
  'invalidtype'   => 'Jenis file tidak valid. Format yang diizinkan: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Unggahan kosong atau file terlalu kecil.',
  'toolarge'      => 'File terlalu besar.',
  'savesuccess'   => 'Notifikasi email kustom berhasil diperbarui.',
  'removesuccess' => 'Notifikasi email kustom berhasil dihapus.',
  'playtest'      => 'Putar notifikasi',
  'hint'          => 'Mengganti suara pesan baru bawaan ketika opsi "Putar suara saat ada pesan baru" diaktifkan.',
];
