<?php
// Íslenska (Ísland)

$labels = [
  'changesound'   => 'Sérsniðin tölvupósttilkynning',
  'uploadsound'   => 'Hlaða upp hljóðskrá',
  'currentsound'  => 'Núverandi tölvupósttilkynning',
  'remove'        => 'Fjarlægja',
  'save'          => 'Vista',
  'invalidtype'   => 'Ógild skráartegund. Leyfilegt: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Tóm upphleðsla eða skráin er of lítil.',
  'toolarge'      => 'Skráin er of stór.',
  'savesuccess'   => 'Sérsniðin tölvupósttilkynning hefur verið uppfærð.',
  'removesuccess' => 'Sérsniðin tölvupósttilkynning hefur verið fjarlægð.',
  'playtest'      => 'Spila tilkynningu',
  'hint'          => 'Þetta kemur í stað sjálfgefins hljóðs fyrir ný skilaboð þegar „Spila hljóð við ný skilaboð“ er virkjað.',
];
