<?php
// 한국어 (대한민국)

$labels = [
  'changesound'   => '사용자 지정 이메일 알림',
  'uploadsound'   => '오디오 파일 업로드하기',
  'currentsound'  => '현재 이메일 알림',
  'remove'        => '삭제',
  'save'          => '저장',
  'invalidtype'   => '잘못된 파일 형식입니다. 허용되는 형식: mp3, ogg, flac, wav, m4a',
  'toosmall'      => '빈 업로드이거나 파일이 너무 작습니다.',
  'toolarge'      => '파일이 너무 큽니다.',
  'savesuccess'   => '사용자 지정 이메일 알림이 성공적으로 업데이트되었습니다.',
  'removesuccess' => '사용자 지정 이메일 알림이 성공적으로 제거되었습니다.',
  'playtest'      => '알림 재생',
  'hint'          => '“새 메일 시 소리 재생” 옵션이 활성화되면 기본 새 메시지 소리가 대체됩니다.',
];
