<?php
// Latviešu (Latvija)

$labels = [
  'changesound'   => 'Pielāgots e-pasta paziņojums',
  'uploadsound'   => 'Augšupielādēt skaņas failu',
  'currentsound'  => 'Pašreizējais e-pasta paziņojums',
  'remove'        => 'Noņemt',
  'save'          => 'Saglabāt',
  'invalidtype'   => 'Nederīgs faila tips. Atļautie formāti: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Tukša augšupielāde vai fails ir pārāk mazs.',
  'toolarge'      => 'Fails ir pārāk liels.',
  'savesuccess'   => 'Pielāgots e-pasta paziņojums veiksmīgi atjaunināts.',
  'removesuccess' => 'Pielāgots e-pasta paziņojums veiksmīgi noņemts.',
  'playtest'      => 'Atskaņot paziņojumu',
  'hint'          => 'Šī opcija aizstāj noklusēto jaunas vēstules skaņu, kad ir ieslēgts “Atskaņot skaņu pie jaunas vēstules”.',
];
