<?php
// Malti (Malta)

$labels = [
  'changesound'   => 'Notifiki ta’ email personalizzata',
  'uploadsound'   => 'Itella’ fajl awdjo',
  'currentsound'  => 'Notifiki ta’ email kurrenti',
  'remove'        => 'Neħħi',
  'save'          => 'Issejvja',
  'invalidtype'   => 'Tip ta’ fajl mhux validu. Permessi: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Upload vojt jew fajl żgħir wisq.',
  'toolarge'      => 'Il-fajl huwa kbir wisq.',
  'savesuccess'   => 'Notifiki ta’ email personalizzata aġġornata.',
  'removesuccess' => 'Notifiki ta’ email personalizzata tneħħiet.',
  'playtest'      => 'Doqq in-notifiki',
  'hint'          => 'Dan jissostitwixxi l-ħoss default ta’ messaġġ ġdid meta "Doqq ħoss għal messaġġ ġdid" ikun attivat.',
];
