<?php
// Polski (Polska)

$labels = [
  'changesound'   => 'Niestandardowe powiadomienie e-mail',
  'uploadsound'   => 'Prześlij plik audio',
  'currentsound'  => 'Bieżące powiadomienie e-mail',
  'remove'        => 'Usuń',
  'save'          => 'Zapisz',
  'invalidtype'   => 'Nieprawidłowy typ pliku. Dozwolone: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Pusty upload lub plik zbyt mały.',
  'toolarge'      => 'Plik zbyt duży.',
  'savesuccess'   => 'Zaktualizowano niestandardowe powiadomienie e-mail.',
  'removesuccess' => 'Usunięto niestandardowe powiadomienie e-mail.',
  'playtest'      => 'Odtwórz powiadomienie',
  'hint'          => 'Zastępuje domyślny dźwięk nowej wiadomości, gdy włączona jest opcja „Odtwarzaj dźwięk przy nowej wiadomości”.',
];
