<?php
// Slovenščina (Slovenija)

$labels = [
  'changesound'   => 'Prilagojeno e-poštno obvestilo',
  'uploadsound'   => 'Naloži zvočno datoteko',
  'currentsound'  => 'Trenutno e-poštno obvestilo',
  'remove'        => 'Odstrani',
  'save'          => 'Shrani',
  'invalidtype'   => 'Neveljavna vrsta datoteke. Dovoljeni formati: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Prazno nalaganje ali datoteka premajhna.',
  'toolarge'      => 'Datoteka je prevelika.',
  'savesuccess'   => 'Prilagojeno e-poštno obvestilo je bilo posodobljeno.',
  'removesuccess' => 'Prilagojeno e-poštno obvestilo je bilo odstranjeno.',
  'playtest'      => 'Predvajaj obvestilo',
  'hint'          => 'Zamenja privzeti zvok za novo sporočilo, ko je omogočena možnost »Predvajaj zvok ob novem sporočilu«.',
];
