<?php
// Shqip (Shqipëri)

$labels = [
  'changesound'   => 'Njoftim email i personalizuar',
  'uploadsound'   => 'Ngarko skedar audio',
  'currentsound'  => 'Njoftimi aktual i email-it',
  'remove'        => 'Hiq',
  'save'          => 'Ruaj',
  'invalidtype'   => 'Lloj skedari i pavlefshëm. Të lejuara: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Ngarkim bosh ose skedari shumë i vogël.',
  'toolarge'      => 'Skedari është shumë i madh.',
  'savesuccess'   => 'Njoftimi i personalizuar i email-it u përditësua me sukses.',
  'removesuccess' => 'Njoftimi i personalizuar i email-it u hoq me sukses.',
  'playtest'      => 'Riprodho njoftimin',
  'hint'          => 'Kjo zëvendëson tingullin e paracaktuar të mesazhit të ri kur është aktiv opsioni «Luaj tingull kur ka mesazh të ri».',
];
