<?php
$labels = [
  'changesound'   => 'Isaziso se-imeyile esenziwe ngokwesiko',
  'uploadsound'   => 'Layisha ifayile yesandi',
  'currentsound'  => 'Isaziso se-imeyile sangoku',
  'remove'        => 'Susa',
  'save'          => 'Gcina',
  'invalidtype'   => 'Uhlobo lwefayile aluvumelekanga. Ezivunyelweyo: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Ukulayishwa akunanto okanye ifayile incinci kakhulu.',
  'toolarge'      => 'Ifayile inkulu kakhulu.',
  'savesuccess'   => 'Isaziso se-imeyile esenziwe ngokwesiko sihlaziyiwe.',
  'removesuccess' => 'Isaziso se-imeyile esenziwe ngokwesiko sisusiwe.',
  'playtest'      => 'Dlala isaziso',
  'hint'          => 'Oku kuthatha indawo yesandi esingagqibekanga somyalezo omtsha xa "Dlala isandi xa kukho umyalezo omtsha" ivuliwe.',
];
