<?php
// NOTE: localized for zh_HK

$labels = [
  'changesound'   => '自訂電郵通知',
  'uploadsound'   => '上載聲音檔案',
  'currentsound'  => '目前電郵通知',
  'remove'        => '刪除',
  'save'          => '儲存',
  'invalidtype'   => '無效的檔案類型。允許格式：mp3、ogg、flac、wav、m4a',
  'toosmall'      => '上載空白或檔案過小。',
  'toolarge'      => '檔案過大。',
  'savesuccess'   => '已更新自訂電郵通知。',
  'removesuccess' => '已刪除自訂電郵通知。',
  'playtest'      => '播放通知',
  'hint'          => '啟用「新電郵播放聲音」時，將會覆寫預設的新電郵提示音。',
];
