<?php
// isiZulu (South Africa)

$labels = [
  'changesound'   => 'Isaziso se-imeyili esenziwe ngokwezifiso',
  'uploadsound'   => 'Layisha ifayela lomsindo',
  'currentsound'  => 'Isaziso se-imeyili samanje',
  'remove'        => 'Susa',
  'save'          => 'Londoloza',
  'invalidtype'   => 'Uhlobo lwefayela aluvumelekile. Okugunyaziwe: mp3, ogg, flac, wav, m4a',
  'toosmall'      => 'Ukulayisha okungenalutho noma ifayela lincane kakhulu.',
  'toolarge'      => 'Ifayela likhulu kakhulu.',
  'savesuccess'   => 'Isaziso se-imeyili esenziwe ngokwezifiso sibuyekeziwe.',
  'removesuccess' => 'Isaziso se-imeyili esenziwe ngokwezifiso sisusiwe.',
  'playtest'      => 'Dlala isaziso',
  'hint'          => 'Lokhu kuthathela indawo umsindo ojwayelekile wombiko omusha uma “Dlala umsindo lapho kunombiko omusha” kuvuliwe.',
];
